version: "3.9"

services:
  backend:
    image: gourav180731/talkspace_backend:latest
    container_name: talkspace_backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: gourav180731/talkspace_frontend:latest
    container_name: talkspace_frontend
    ports:
      - "8080:80"
    restart: always
