import { axiosInstance } from "./axios";
export const pinChat = (chatId:string, chatType="direct")=> axiosInstance.post("/chat-management/pin", {chatId, chatType});
export const unpinChat = (chatId:string)=> axiosInstance.delete(`/chat-management/pin/${chatId}`);
export const archiveChat = (chatId:string, chatType="direct")=> axiosInstance.post("/chat-management/archive", {chatId, chatType});
export const unarchiveChat = (chatId:string)=> axiosInstance.delete(`/chat-management/archive/${chatId}`);
export const getArchivedChats = ()=> axiosInstance.get("/chat-management/archived");
export const muteChat = (chatId:string, duration:string, chatType="direct")=> axiosInstance.post("/chat-management/mute", {chatId, duration, chatType});
export const unmuteChat = (chatId:string)=> axiosInstance.delete(`/chat-management/mute/${chatId}`);
export const toggleFavourite = (chatId:string, chatType="direct")=> axiosInstance.post("/chat-management/favourite", {chatId, chatType});
export const toggleLock = (chatId:string, chatType="direct")=> axiosInstance.post("/chat-management/lock", {chatId, chatType});
export const setDisappearing = (chatId:string, duration:string, chatType="direct")=> axiosInstance.post("/chat-management/disappearing", {chatId, duration, chatType});
export const reportUser = (chatId:string, reason="spam")=> axiosInstance.post("/chat-management/report", {chatId, reason});
export const addToList = (chatId:string, listName:string)=> axiosInstance.post("/chat-management/add-to-list", {chatId, listName});
export const getLists = ()=> axiosInstance.get("/chat-management/lists");
export const toggleStar = (messageId:string, chatId:string)=> axiosInstance.post("/chat-management/star", {messageId, chatId});
export const getStarred = ()=> axiosInstance.get("/chat-management/starred");
export const scheduleCall = (chatId:string, scheduledAt:string, chatType="direct")=> axiosInstance.post("/chat-management/schedule-call", {chatId, scheduledAt, chatType});
export const getScheduledCalls = ()=> axiosInstance.get("/chat-management/scheduled-calls");
